### ISSUE TITLE
Minsdk

### ISSUE THREAD

**Issue by ghost** [fenjuly/SpinnerLoader#1]
Is the minsdk only to be 16?

**Comment by fenjuly** [comment]
No, you can set another version below 16, but I havn't tested it before.

278956952 notifications@github.com于2015年11月4日周三 00:52写道：

**Comment by ghost** [comment]
Hi,

I include it into my project and the minsdk of my project is 15, then there is an error show the spninerloader minsdk is 16, the project's minsdk should above 15 on android studio. How can i to solve it? Please give me a hand! Thanks

Armstrong

**Comment by fenjuly** [comment]
Try to find the file `/library/build.gradle`, and locate at this line

``` gradle
defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
```

Then set the `minSdkVersion` to 15.

**Comment by ghost** [comment]
could you update your code in git hub? so, others need not to download the lib and update the /library/build.gradle

**Comment by fenjuly** [comment]
ok, and have your problem been solved?

278956952 notifications@github.com于2015年11月5日周四 14:18写道：

**Comment by ghost** [comment]
Yes, Thank you very much! I will update my project soon.
